MyBlog/MyBlog/Controllers/PlayGroundController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    public class PlayGroundController : Controller
    {
        private Models.db_9ae46c_myblogEntities suMain = new db_9ae46c_myblogEntities();
        private IEnumerable<playground> _playground = new List<playground>();
        //
        // GET: /PlayGround/

        public ActionResult Index()
        {
            _playground = from p in suMain.playgrounds
                          orderby p.id ascending
                          select p;
            return View(_playground.ToList());
        }

        public ActionResult Edit(int id)
        {
            playground editObject = (from p in suMain.playgrounds
                                     where p.id == id
                                     select p).FirstOrDefault();
            ViewBag.id = id;
            return View(editObject);
        }


        public ContentResult Update(int id, string text)
        {
            using (var context = new db_9ae46c_myblogEntities())
            {
                playground _se = context.playgrounds.FirstOrDefault(m => m.id == id);
                try
                {
                    _se.text = text;
                    context.SaveChanges();
                }
                catch (Exception e)
                {

                }
            }
            return Content("Success");
        }

        public ContentResult New(string text)
        {
            using (var context = new db_9ae46c_myblogEntities())
            {
                try
                {
                    playground insert = new playground()
                    {
                        text = text
                    };
                    context.playgrounds.AddObject(insert);
                    context.SaveChanges();
                }
                catch (Exception e)
                {

                }
            }
            return Content("Success");
        }

        public ContentResult Delete(int id, bool isLastRowDeleted)
        {
            using (var context = new db_9ae46c_myblogEntities())
            {
                var delete = (from s in suMain.playgrounds
                           where s.id == id
                           select s).FirstOrDefault();
                playground del = context.playgrounds.FirstOrDefault(m => m.id == id);
                try
                {
                    // delete row
                    context.playgrounds.DeleteObject(del);
                    context.SaveChanges();

                    // save row if last row
                    if (isLastRowDeleted)
                    {
                        New("");
                    }
                }
                catch (Exception e)
                {

                }
            }
            return Content("Success");
        }

        [HttpPost]
        public ActionResult ReloadEditPartial()
        {
            _playground = from p in suMain.playgrounds
                          orderby p.id ascending
                           select p;
            return PartialView("_PlayGroundPartial", _playground.ToList());
        }

        public ContentResult GetRowCount()
        {
            var count = (from s in suMain.playgrounds
                         select s).Count();
            try
            {

            }
            catch (Exception e)
            {

            }
            return Content(count.ToString());
        }
    }
}

MyBlog/MyBlog/Views/PlayGround/Edit.cshtml
@model MyBlog.Models.playground
@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<style type="text/css">
#editForm{
 /*background-color:Gray;*/
}
</style>
<script type="text/javascript">

    function ReloadPartial() {
        $.ajax({
            url: '@Url.Action("ReloadEditPartial", "PlayGround")',
            data: {},
            type: 'POST',
            success: function (data) {
                $('#playGroundMsg').html(data);
                $("#popupwindow").dialog("close");
                $('#playground_popupwindow').dialog("close");
                return true;
            }
        });
    }

    function getRowCount() {
        var toReturn = null;
        $.ajax({
            url: "PlayGround/GetRowCount",
            async: false,
            cache: false,
            type: 'Get',
            dataType: 'html',
            data: {}
        }).success(function (data) {
            toReturn = data;
        }).error(function (xhr, status) {
            LoadMsg(xhr.responseText);
            return false;
        });
        return toReturn;
    }

    function SaveNew() {
        //        var modelDataJSON = '@Html.Raw(Json.Encode(Model))';
        var Text = $("#text").val();
        if (Text == "") {
            LoadMsg('Please enter value.');
            return false;
        }

        $("#popupwindow").dialog({
            autoOpen: false,
            modal: true,
            show: "fade",
            height: "200",
            width: "300px",
            title: "Save New?",
            buttons: {
                "Save New": function () {
                    $.ajax({
                        url: "PlayGround/New",
                        async: false,
                        cache: false,
                        type: 'Get',
                        dataType: 'html',
                        data: { text: Text }
                    }).success(function (data) {
                        if (data == "Success") {
                            ReloadPartial();
                            return true;
                        }
                        else {
                            LoadMsg("Could not save, error.");
                            return false;
                        }
                    }).error(function (xhr, status) {
                        LoadMsg(xhr.responseText);
                        return false;
                    });
                },
                "Cancel": function () {
                    $(this).dialog("close");
                }
            }
        });
        $("#popupwindow").html("Do you want to Save New?");
        $("#popupwindow").dialog("open");
    }

    function Update() {
        var Text = $("#text").val();
        if (Text == "") {
            LoadMsg('Please enter value.');
            return false;
        }
        var id = '@ViewBag.id';

        $("#popupwindow").dialog({
            autoOpen: false,
            modal: true,
            show: "fade",
            height: "200",
            width: "300px",
            title: "Update?",
            buttons: {
                "Update": function () {
                    $.ajax({
                        url: "PlayGround/Update",
                        async: false,
                        cache: false,
                        type: 'Get',
                        dataType: 'html',
                        data: { id: id, text: Text }
                    }).success(function (data) {
                        if (data == "Success") {
                            ReloadPartial();
                            return true;
                        }
                        else {
                            LoadMsg("Could not save, error.");
                        }
                    }).error(function (xhr, status) {
                        LoadMsg(xhr.responseText);
                        return false;
                    });
                },
                "Cancel": function () {
                    $(this).dialog("close");
                }
            }
        });
        $("#popupwindow").html("Do you want to Update?");
        $("#popupwindow").dialog("open");
    }

    function Delete() {
        var id = '@ViewBag.id';
        var isLastRow = false;
        if (getRowCount() == "1") {
            isLastRow = true;
            //LoadMsg('One row must exist');
        }

        $("#popupwindow").dialog({
            autoOpen: false,
            modal: true,
            show: "fade",
            height: "200",
            width: "300px",
            title: "Delete?",
            buttons: {
                "Delete": function () {
                    $.ajax({
                        url: "PlayGround/Delete",
                        async: false,
                        cache: false,
                        type: 'Get',
                        dataType: 'html',
                        data: { id: id, isLastRowDeleted: isLastRow }
                    }).success(function (data) {
                        if (data == "Success") {
                            ReloadPartial();
                            return true;
                        }
                        else {
                            LoadMsg("Could not save, error.");
                            return false;
                        }
                    }).error(function (xhr, status) {
                        LoadMsg(xhr.responseText);
                    });
                },
                "Cancel": function () {
                    $(this).dialog("close");
                }
            }
        });
        $("#popupwindow").html("Do you want to Delete?");
        $("#popupwindow").dialog("open");
    }
</script>

    @using (Html.BeginForm())
    {
        <div id="editForm">
        @Html.ValidationSummary(true)
        <table>
        <tr>
        <td>
            @Html.TextBoxFor(model => model.text)
        </td>
        </tr>
        </table>
        <input type="button" value="Update" onclick="Update()"/>
        <input type="button" value="Save New" onclick="SaveNew()"/>
        <input type="button" value="Delete" onclick="Delete()"/>
        </div>
    }

MyBlog/MyBlog/Views/PlayGround/Index.cshtml
@{
    ViewBag.Title = "Play Ground";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <style type="text/css">
        .playGround {
            /*margin-left:40%;*/
        }
    </style>

</head>

<body>
    <br />
    <h2>Playground</h2>
    <div class="playGround">
        <p>
            Here is a small project that I started for fun. This table stores only one data per row into the table in my database but you can add, edit, or delete each rows as you see fit.
        </p>
    </div>
    <div id="playGroundMsg" class="playGround">
        @Html.Partial("_PlayGroundPartial")
    </div>
</body>
</html>